### PR TITLE
Issue 213: Empty loot in Lootsplitter throws exception

### LINKED ISSUE #213: Empty loot on lootsplitter throws exception
Handle the empty case there bud.
_(Generally not a problem as loot-splitting bosses usually have a full loot table, but this is a general robustness issue)_

### PR DESCRIPTION
**Pull request by Veritania**

### CODE REVIEW

**Comment by MikeJeffers** [comment]
Another PR already!  😋

**Comment by Veritania** [comment]
Yep! It's fun to explore :)

[LootGenerator.cs L15-L18](https://github.com/Veritania/PerpetuumServer/blob/ba8c98559395bf294175d7e49a4b9e5afb87b3b5/src/Perpetuum/Services/Looting/LootGenerator.cs#L15-L18)
If a null is passed to the LootGenerator here, do we prefer to silently correct the mistake and set it to an empty list, or would you prefer something like `throw new PerpetuumException(ErrorCodes.LootItemNotFound);` or another/new ErrorCode instead?

**Comment by MikeJeffers** [comment]
> 
> 
> Yep! It's fun to explore :)
> 
> [LootGenerator.cs L15-L18](https://github.com/Veritania/PerpetuumServer/blob/ba8c98559395bf294175d7e49a4b9e5afb87b3b5/src/Perpetuum/Services/Looting/LootGenerator.cs#L15-L18)
> If a null is passed to the LootGenerator here, do we prefer to silently correct the mistake and set it to an empty list, or would you prefer something like `throw new PerpetuumException(ErrorCodes.LootItemNotFound);` or another/new ErrorCode instead?

No, the case to throw an error would *typically* be in a response handler (or the callstack of one) such that the error is returned to the client to inform the player (think: 400+ web codes)

The case this PR is actually solving is something that just throws in the course of a server-side thread when generating loot - which aborts a big transaction too rolling back everything about the kill unrelated to the loot generation.  It only happens when a boss does loot splitting, but still and error worth handling so the rest of the kill transaction can proceed and commit.  There might be a boss npc with no loot.. who knows.

**Review by MikeJeffers — APPROVED** [review]
Looks good!

**Pull request merged**
