### PR TITLE
New Player Starting NIC/EP

### PR DESCRIPTION
**Pull request by aqpanaciy**
Pull request target #310 issues. I suggest using a config file *pereptuum.ini* for storing parameters:
- using NIC/EP for new player from server config file, or default value if they are not specified in the file
- using [this](https://stackoverflow.com/questions/29611445/default-value-for-missing-properties-with-json-net) solution for default value.

### CODE REVIEW

**Comment by MikeJeffers** [comment]
This is excellent.  Good call putting in the ini, db probably overkill for loading constants.  Defaults to ensure consistent behaviour with old inis really seals this as a safe PR to merge!  Thank you for your contribution! 💯

Will do closer look and merge shortly, but no notes so far.

**Review by MikeJeffers — APPROVED** [review]

**Comment by aqpanaciy** [comment]
Was cleaning brunches and accidentally deleted this pull request :(
Restored it.

**Comment by MikeJeffers** [comment]
> Was cleaning brunches and accidentally deleted this pull request :( Restored it.

Thanks for that!  
For now I'll merge it because it won't affect deployed code (to my knowledge) with or without your provided configuration options.

Also if you are looking to directly contribute/join the team, make sure the team knows you should be added to the org.  I am not an active maintainer any longer, so the more that can directly contribute, review, and merge - the better!

**Comment by MikeJeffers** [comment]
Congrats on your first contribution to the OPP fork @aqpanaciy ! :tada: :rocket:

**Pull request merged**
