### PR TITLE
Event System + SAP-NPCs

### LINKED ISSUE #165: Event System (NPC)
Used for outpost guardian, and potentially pitboss/bosses.

Implement a system that can provide an eventful, or semi-eventful action execution when an NPC event occurs.

The action interface/callback should be generic enough to allow for configurable actions to be added to specific NPCs (presence, or flock, or specific npc... ?)
And to allow for hooks for onSpawn, and onDeath at least.

Use cases to support:
Log something to a table - like an API announced event of an NPC spawning or dying
Increase or decrease the stability of some outpost.

### PR DESCRIPTION
**Pull request by MikeJeffers**
Closes: https://github.com/OpenPerpetuum/OP-Project/issues/165
REQUIRES: https://github.com/OpenPerpetuum/OPDB/pull/168
Really bare bones right now, but the envisioned design is:
NPC on some event (death in this case, but can be arbitrary) emits a message on some event bus.  Other Listeners are notified of each new message, and handle them accordingly.  

Simple case:
 - NPC dies
 - Create Message for display in chat, wrap in EventMessage, and push onto message queue handled by the EventListeningService
 - On a separate thread, check if any messages are on the queue, pop if there are and notify all subscribed listeners with the message
 - Each EventProcessor then handles the message as notified - most cases ignoring.
 - The ChatEcho processor will echo out to a chat channel a message as prepared by the NPC.

~~Fun TODO: Make this chat echo to vicinity - haven't figured that out yet.~~
Got it to publish to Vicinity chat - but it doesn't automatically update on client... bit odd.

The primary use case of this system (right now) is to allow an NPC death to affect an Outpost's stability.
Feedback welcome on how a particular NPC affects what outpost.  (Right now it checks by specialType, which we can SAP-boss to, and closest outpost).

Design Team TODOs: (As it pertains to values and logic in this PR)
 - What stability points does Guardian kill give?
 - What relations/ownership status affect the points given/taken from stability? (Owners/allies still get negative stability if they kill their own Guardian?)

### CODE REVIEW

**Comment by MikeJeffers** [comment]
Meant to make this a draft PR =/

**Comment by nref-dan** [comment]
Had a chat with Null yesterday; intent is to extend the presence system to include ownership. That way an outpost can "own" a boss, creating a neat connection between them.

**Comment by MikeJeffers** [comment]
> 
> 
> Had a chat with Null yesterday; intent is to extend the presence system to include ownership. That way an outpost can "own" a boss, creating a neat connection between them.

I am slating this for a later feature - scope bloat on this PR.  The Boss relation to an outpost can be handled directly with a table for now.

**Comment by MikeJeffers** [comment]
@clouths @Ketsuekiame initial reviews here welcome - there is a lot to look at.

Things that will be changed soon: BossInfo will include the stability affect points from the DB directly, and will determine +/- effect.

**Review by nref-dan — APPROVED** [review]

**Comment by MikeJeffers** [comment]
[SAP NPCs](https://trello.com/c/uYyjagpq/1-sap-npcs)

**Comment by MikeJeffers** [comment]
@LoyalServant @clouths @Ketsuekiame
There have been significant changes - please re-review as you can.  Many other features will be leveraging this event system.

**Comment by MikeJeffers** [comment]
Fixes: https://github.com/OpenPerpetuum/PerpetuumServer/issues/111

**Pull request merged**
